{% set python_min = "3.10" %}
package:
  name: ro-yolov7
  version: "0.8.0"

source:
  path: ..

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  entrypoints:
    - ro_yolov7_train=ro_yolov7.train:main
    - ro_yolov7_convert_from_yolov7=ro_yolov7.tools.convert_from_yolov7:main
    - ro_yolov7_convert_pytorch_to_onnx=ro_yolov7.tools.convert_pytorch_to_onnx:main

requirements:
  build:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy >=2.0
    - opencv
    - pillow
    - pyyaml
    - requests
    - scipy
    - pytorch
    - tifffile
    - torchvision
    - tqdm
    - onnx
    - onnxscript

test:
  requires:
    - pip
    - python {{ python_min }}.*
  commands:
    - pip check
    - ro_yolov7_train --help
    - ro_yolov7_convert_from_yolov7 --help
    - ro_yolov7_convert_pytorch_to_onnx --help
    - test -f ${SP_DIR}/ro_yolov7/yolov7-tiny.pt
    - test -f ${SP_DIR}/ro_yolov7/cfg/training/yolov7-tiny.yaml
    - test -f ${SP_DIR}/ro_yolov7/data/hyp.scratch.tiny.yaml
  imports:
    - ro_yolov7

about:
  home: https://github.com/WongKinYiu/yolov7
  license: GPL-3.0-only
  license_file: LICENSE.md
  summary: YOLOv7 -- Trainable bag-of-freebies sets new state-of-the-art for real-time object detectors
